// Optional browser verification: PLAYWRIGHT_MODULE=/absolute/playwright/index.mjs VIEWER_URL=... node test/browser.mjs
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1200,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.VIEWER_URL);await page.waitForSelector('.agent');assert.equal(await page.locator('#mode').textContent(),'Sample');await page.locator('.agent').nth(1).click();assert.match(await page.locator('#detail').textContent(),/Implement board interactions/);
await page.locator('#scrub').fill('14');assert.match(await page.locator('#detail').textContent(),/Needs correction/);await page.locator('#scrub').fill('20');assert.match(await page.locator('#detail').textContent(),/Accepted/);
await page.locator('#export').click();assert(await page.locator('#export-dialog').isVisible());const download=page.waitForEvent('download');await page.locator('#download-export').click();const file=await (await download).path();const safe=JSON.parse(await fs.readFile(file,'utf8'));assert(safe.redacted);assert(!JSON.stringify(safe).includes('keyboard'));await page.locator('#import').setInputFiles(file);assert.equal(await page.locator('#mode').textContent(),'Sample');
const bad={schemaVersion:1,mode:'Recorded',events:[{schemaVersion:1,eventId:'x',agentId:'a',at:'2026-09-28T12:00:00Z',type:'agent.created',data:{title:'<img src=x onerror=alert(1)>'}}]};await page.locator('#import').setInputFiles({name:'untrusted.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});assert.equal(await page.locator('#detail img').count(),0);assert.match(await page.locator('#detail').textContent(),/<img/);
await page.locator('#live').click();await page.locator('.agent').nth(1).click();await page.locator('#scrub').fill('10');await page.screenshot({path:'.local/desktop.png',fullPage:true});
for(const width of [390,320]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`)}await page.screenshot({path:'.local/mobile.png',fullPage:true});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.screenshot({path:'.local/dark-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: selection, correction, acceptance, export/import, XSS text rendering, 320px/390px layout, no browser errors');}finally{await browser.close()}
