#!/usr/bin/env node
// Build the self-contained plugin runtime in ./server, so an installed plugin
// needs Node.js but no dependency installation (the same approach as the
// official Bits & Bolts example):
// Paths below are relative to the plugin folder (plugins/codex-on-crack-panel):
//   server/panel.mjs  CLI + controller + localhost fallback + MCP server (SDKs bundled)
//   server/lead.mjs   the existing external-lead adapter CLI, bundled unchanged
//   server/app.html   the MCP App UI as one HTML file (script and styles inline)
//   server/ui/*       localhost fallback assets, copied from src/ui
// Dependencies come from the pinned lockfile (`npm ci`). Output is deterministic.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// The plugin folder holds only runtime files; the bundle is written into it.
const PLUGIN = path.resolve(ROOT, '../plugins/codex-on-crack-panel');
const OUT = path.join(PLUGIN, 'server');
const LEAD = path.resolve(ROOT, '../plugins/codex-on-crack/skills/crack/scripts/lead.mjs');
const HEADER = '// Generated by scripts/build.mjs from src/ and the pinned dependencies. Do not edit.\n';
const NODE_BANNER = `${HEADER}import { createRequire as __panelCreateRequire } from 'node:module';\nconst require = __panelCreateRequire(import.meta.url);`;
const UI_ASSETS = ['index.html', 'panel.mjs', 'http-entry.mjs', 'panel.css', 'icon.svg'];

// Bundling gives every module the bundle's import.meta.url, so a library
// module's own "am I the CLI?" check would wrongly fire. Neutralise exactly
// that check in non-entry modules; fail the build if the pattern changes.
const ENTRY_CHECK = 'function isEntrypoint(argv = process.argv, moduleUrl = import.meta.url)';
const LIBRARY_CLIS = new Set([path.resolve(ROOT, '../plugins/codex-on-crack/skills/crack/viewer/serve.mjs'), path.resolve(ROOT, '../plugins/codex-on-crack/skills/crack/viewer/bridge.mjs')]);
const libraryEntrypoints = {
  name: 'library-entrypoints',
  setup(builder) {
    builder.onLoad({ filter: /\.mjs$/ }, (args) => {
      if (!LIBRARY_CLIS.has(args.path)) return undefined;
      const source = fs.readFileSync(args.path, 'utf8');
      if (source.split(ENTRY_CHECK).length !== 2) throw new Error(`${args.path}: expected exactly one entrypoint check`);
      return { contents: source.replace(ENTRY_CHECK, "function isEntrypoint(argv = process.argv, moduleUrl = 'bundled:library')"), loader: 'js' };
    });
  },
};

const common = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'eof',
  charset: 'utf8',
  logLevel: 'warning',
  absWorkingDir: ROOT,
  plugins: [libraryEntrypoints],
};

export async function buildAll({ out = OUT } = {}) {
  const OUT_DIR = out;
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(path.join(OUT_DIR, 'ui'), { recursive: true });

  await build({ ...common, entryPoints: ['src/cli.mjs'], outfile: path.join(OUT_DIR, 'panel.mjs'), minify: true, banner: { js: NODE_BANNER } });
  await build({ ...common, entryPoints: [LEAD], outfile: path.join(OUT_DIR, 'lead.mjs'), minify: false, banner: { js: HEADER } });
  // esbuild keeps each entry's own shebang, so the banners add none.

  const app = await build({
    entryPoints: ['src/ui/mcp-entry.mjs'], bundle: true, write: false, format: 'iife', platform: 'browser',
    target: 'es2022', minify: true, legalComments: 'none', charset: 'utf8', logLevel: 'warning', absWorkingDir: ROOT,
  });
  const script = app.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const sdkStyles = fs.readFileSync(path.join(ROOT, 'node_modules/@openai/mcp-extensions/styles.css'), 'utf8');
  const panelStyles = fs.readFileSync(path.join(ROOT, 'src/ui/panel.css'), 'utf8');
  const html = [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Codex on Crack</title>',
    `<style>\n${sdkStyles.replace(/<\/style/gi, '<\\/style')}\n</style>`,
    `<style>\n${panelStyles.replace(/<\/style/gi, '<\\/style')}\n</style>`,
    '</head>',
    '<body>',
    '<div id="app" aria-live="polite"></div>',
    `<script>${script}</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(OUT_DIR, 'app.html'), html);
  const replay = await build({entryPoints:['src/ui/replay-entry.mjs'],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',minify:true,legalComments:'none',charset:'utf8',absWorkingDir:ROOT});
  const replayScript=replay.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
  const replayHtml=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>Build replay</title><style>${panelStyles}
.replay-controls{position:sticky;top:0;z-index:10;background:var(--p-bg);border-bottom:1px solid var(--p-line-strong);padding:14px 20px;display:flex;gap:10px;flex-wrap:wrap;align-items:center}.replay-controls input{flex:1;min-width:120px}.replay-controls strong{flex-basis:100%;font-size:12px}.replay-notice{padding:8px 20px;font-size:11px;color:var(--p-fg-2)}.session-card{padding:20px;margin:16px;border:1px solid var(--p-line);border-radius:10px}.session-card h2{font-size:16px}.session-card p,.session-card ul{margin-top:10px}.session-card pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}#session-view>.foot{padding:20px}#coverage{padding:20px;border-top:1px solid var(--p-line)}
</style><body><div class="replay-controls"><strong id="capture-state"></strong><button id="previous" class="button">Previous</button><button id="play" class="button primary">Play</button><button id="next" class="button">Next</button><input id="position" aria-label="Replay position" type="range" min="0" value="0"><span id="time" class="small"></span><select id="speed" aria-label="Playback speed"><option value="1">1×</option><option value="5">5×</option><option value="20" selected>20×</option><option value="60">60×</option></select><button data-view="panel" aria-pressed="true" class="button">Codex on Crack</button><button data-view="sessions" aria-pressed="false" class="button">Recorded sessions</button><button data-view="checkpoints" aria-pressed="false" class="button">Checkpoints</button></div><p id="gaps" class="replay-notice" role="status"></p><div id="app"></div><div id="session-view" hidden></div><div id="checkpoint-view" hidden></div><p id="coverage" class="foot"></p><script type="application/json" id="recording-data"><!--RECORDING_DATA--></script><script>${replayScript}</script></body></html>`;
  fs.writeFileSync(path.join(OUT_DIR,'replay.html'),replayHtml);

  for (const asset of UI_ASSETS) fs.copyFileSync(path.join(ROOT, 'src/ui', asset), path.join(OUT_DIR, 'ui', asset));
  fs.copyFileSync(path.join(ROOT, 'src/ui/icon.svg'), path.join(OUT_DIR, 'icon.svg'));
  fs.chmodSync(path.join(OUT_DIR, 'panel.mjs'), 0o755);
  fs.chmodSync(path.join(OUT_DIR, 'lead.mjs'), 0o755);
  return fs.readdirSync(OUT_DIR, { recursive: true }).sort();
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const files = await buildAll();
  process.stdout.write(`Built ${files.length} entries in server/: ${files.join(', ')}\n`);
}
